# Generated by Django 3.1.2 on 2020-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tags_interested_users'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_tags',
            field=models.ManyToManyField(blank=True, to='tags.Tags'),
        ),
    ]
