# Generated by Django 3.1.2 on 2020-12-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tags_interested_users'),
        ('users', '0002_profile_interested_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interested_tags',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='tags.Tags'),
        ),
    ]
