# Generated by Django 3.1.2 on 2020-10-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200914_2320'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('user', 'title')},
        ),
    ]
