# Generated by Django 3.1.2 on 2020-10-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='current_money',
        ),
    ]
