# Generated by Django 3.1.2 on 2020-10-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_remove_campaign_num_of_backers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign', to='campaigns.campaign'),
        ),
    ]
