# Generated by Django 3.1.2 on 2020-10-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20201018_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, default='default_campaign_pic.png', upload_to='campaign_pics'),
        ),
    ]
