site_name: Grasshopperfund Docs

repo_url: https://github.com/grasshopperfund/grasshopperfund
repo_name: grasshopperfund/grasshopperfund

theme:
  name: material
  palette:
    scheme: slate
    primary: green

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/
#  - markdown_include.include:
#      base_path: docs

extra_css:
  - css/termynal.css

extra_javascript:
  - js/termynal.js
  - js/custom.js


# page tree
nav:
  - Home: index.md
  - Getting Started:
    - Onboarding: Onboarding.md
    - Installation: Installation.md
    - Git Workflow: Git-Workflow.md
    - Django: Django.md
  - Database: Database.md
  - Change log:
    - Project Restructure: project-restructure.md
    - Suggestions: suggestions.md
