site_name: Grasshopperfund Docs

repo_url: https://github.com/grasshopperfund/grasshopperfund
repo_name: grasshopperfund/grasshopperfund

theme:
  name: material
  palette:
    scheme: preference
    primary: green

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/
#  - markdown_include.include:
#      base_path: docs

extra_css:
  - css/termynal.css

extra_javascript:
  - js/termynal.js
  - js/custom.js


# page tree
nav:
  - Home: index.md
  - Getting Started:
    - Onboarding: Onboarding.md
    - Installation: Installation.md
    - Git Workflow: Git-Workflow.md
    - Django: Django.md
  - Database: database.md
  - Frontend: frontend.md
  - Change log:
    - added Organizations and Posts: change-log/added-organizations-and-posts.md
    - CSS Setup: change-log/css-setup.md
    - Created donation: changelog/created-donation.md
    - Added Tags: change-log/added-tags.md
    - Added Organizations: change-log/added-organizations.md
    - Project Restructure: change-log/project-restructure.md
    - Suggestions: change-log/suggestions.md
