# Generated by Django 3.1.2 on 2020-12-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='tags', to='campaigns.Campaign')),
            ],
        ),
    ]
