# Generated by Django 3.1.2 on 2020-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='interested_users',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
