# Generated by Django 3.1.2 on 2020-12-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tags_interested_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='interested_users',
        ),
    ]
