# Generated by Django 3.1.2 on 2020-12-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20201127_1431'),
        ('users', '0003_auto_20201201_0019'),
        ('tags', '0003_remove_tags_interested_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
