# Generated by Django 3.1.2 on 2020-12-07 00:39

from django.db import migrations, models



def populate_tags(apps, schema_editor):
    Tag = apps.get_model('tags', 'tag')

    tag_names = [
        'Advertising',
        'Biotech',
        'Cybersecurity',
        'Data Analytics',
        'E-Commerce',
        'Education',
        'Fashion',
        'Finance',
    ]

    for tag_name in tag_names:
        Tag.objects.create(name=tag_name)

class Migration(migrations.Migration):


    dependencies = [
        (
            'tags',
            '0001_initial'
        ),
    ]

    operations = [
        migrations.RunPython(populate_tags)
    ]
