# Generated by Django 3.1.2 on 2020-11-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tag',
            field=models.ManyToManyField(related_name='campaign', to='tags.Tags'),
        ),
    ]
