# Generated by Django 3.1.2 on 2020-12-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_campaigns'),
        ('campaigns', '0002_auto_20201201_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='tag',
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(related_name='campaigns', to='tags.Tag'),
        ),
    ]
