# Generated by Django 3.1.2 on 2020-11-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_tag'),
        ('campaigns', '0002_auto_20201112_1310'),
    ]

    operations = [
    ]
