# Generated by Django 3.1.2 on 2020-11-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_delete_post'),
        ('campaigns', '0003_merge_20201116_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('organization', 'title')},
        ),
    ]
